### ISSUE TITLE
Substituition for setModelDisplay()

### ISSUE THREAD

**Issue by eng-luciano-julien** [IFCjs/web-ifc-three#23]
Hi,
Great project!
I am looking for guidance about the change in the library of the functions setModelDisplay() which was deleted.
I was using setModelDisplay to configure transparency of the whole model and setItemsDisplay to color some elements to highlight.
Its seems the function createSubset() substitutes setItemsDisplay(), is there a way to setModelDisplay() or is it planned to implement similar function?

Thanks in advance

**Comment by agviegas** [comment]
Hey @eng-luciano-julien sorry, we had to change the API, but this version should remain stable. Indeed, createSubset() is the way to go now. Currently, `ifcLoader` creates a single geometry of the entire IFC model, but saves the individual geometries in memory before merge. These individual geometries can be used to create subsets of the model (e.g. the entire first floor geometry). This is because it is the only way to handle large models at 60 fps. 

If you want to change the appearance of the whole model it generates when loading the IFC, you can simply access the materials of the generated mesh and change them to whatever you want (e.g. make them transparent).

**Comment by eng-luciano-julien** [comment]
@agviegas thank you! I managed to do it accessing the materials.
