### ISSUE TITLE
Problem when rendering IfcBuildingElementProxy which are rectangle extruded shapes

### ISSUE THREAD

**Issue by favreau84** [IFCjs/web-ifc-three#30]
## Note
Initially https://github.com/tomvandig/web-ifc/issues/69

## Context

In this construction project, one company (company A) is managing all the openings changes from one Revit digital mockup. Every time a change occurs, the company A shares one IFC files with all the up-to-date openings. Consulting companies, like structural engineering consultants, need to update the execution blueprints from this IFC. 

## Problem

When using the web-ifc-three lib to render the openings in 3D, the opening shapes do not appear to be regular rectangles. However, this is the case with the BIMcollab software.

<img width="414" alt="element" src="https://user-images.githubusercontent.com/18169247/127193693-96363e4a-f6de-4c99-b740-dd0609694150.png">

The openings are mainly extruded shapes.

<img width="1279" alt="openings" src="https://user-images.githubusercontent.com/18169247/127193785-2d61d6fc-2e66-48f5-9f69-464b83d07b56.png">

#### Problem in one dimension

Using the orthographic camera in the Y and X direction, it appears that the "weird" shapes pb is limited to the view from above. It is like the extrusion did not work correctly.

<img width="613" alt="orthographic" src="https://user-images.githubusercontent.com/18169247/127194819-72dd839e-1ef2-48ce-b597-c5261d5aaf02.png">

## Files

[openings.ifc.zip](https://github.com/tomvandig/web-ifc/files/6887335/openings.ifc.zip)

#### Note

The model is globally translated far away from the origin... To be sure to view it with Three.js, the camera should target the center of its bounding box.

**Comment by tomvandig** [comment]
Short outline of the problem: IFC has enough precision in its serialized form to represent rather big numbers (I guess doubles), combined with allowing composition of transformations, which makes it possible to accurately represent quite large distances. When reading in the IFC, we convert it to (less accurate) floating point, for two reasons: it uses half the memory, and your GPU can't handle doubles anyway, so you there's no reason to keep them around.

Normally this is not a problem, but if the IFC model is far away, the coordinates are too big to be represented accurately in floats, and you get the kind of distortions visible above. What we can do to prevent this is apply a transformation before converting to floats, this way all the numbers are small and floating point accuracy is sufficient. This is what happens with the COORDINATE_TO_ORIGIN flag in web-ifc, which basically takes the first point in the IFC and translates the entire model such that this first point lies at the origin (0,0,0).

The trouble is that you then lose the relative positioning of models if you attempt to load in multiple, because they are now all coordinated at the origin. This can in turn be solved by partially undoing the first transformation, by reapplying the original relative transformation between the models. It's a little annoying, but not particularly complicated, and requires some more code in both repositories

A neater way to do this is to look at the transformation of the site, and apply the inverted transformation to all elements in the model. This way you can choose to transform all models identically and they will appear correctly relative to eachother. This can be done right with the current web-ifc code, but only works for models where the site is far away, I'm not sure if that covers all cases.

There's probably more ways to solve this problem, let me know what you think.

**Comment by vegarringdal** [comment]
Maybe web-ifc could give us how much it moves it when using COORDINATE_TO_ORIGIN.
So we can adjust for it when loading next file ?

**Comment by favreau84** [comment]
@tomvandig , great, it was exactly that. The ifcSite was indeed far far away from the origin of the WorldCoordinateSystem.

<img width="511" alt="Capture d’écran 2021-07-27 à 23 48 50" src="https://user-images.githubusercontent.com/18169247/127232494-94ba5602-de94-4fa3-ae82-fdd63af0ef8c.png">

I found an article which is describing this discrepancy problem : [here](https://thinkmoult.com/ifc-coordinate-reference-systems-and-revit.html)

### Quick & dirty
As the article suggests, I manage to display correctly the model by setting from the editor the origin of the IfcSite to 0,0. I don't have enough knowledge on the location inheritance between Project>Site>Building>Storey>... to identify side effects, but the model is displayed correctly.

<img width="636" alt="Capture d’écran 2021-07-27 à 23 56 55" src="https://user-images.githubusercontent.com/18169247/127233069-49da2f5e-9359-4614-99e7-15b55a686a00.png">

### COORDINATE_TO_ORIGIN
That's a clear and simple to understand solution. **Is it possible to call this flag with the web-ifc-loader** ? As @vegarringdal suggests, getting the transformation as an output would be great to adjust next loadings.

### Inverted transformation
@tomvandig, my understanding is way to superficial to provide any feedback on this option. When you say that the inverted transformation can be applied to every element, does it mean that the coordinates of the relative placement of these elements will then become large numbers ? Don't we fall back in the same scenario ?
<img width="522" alt="Capture d’écran 2021-07-28 à 00 15 33" src="https://user-images.githubusercontent.com/18169247/127235419-42be8393-b997-4bb9-998a-51ebd62fc5ab.png">

**Comment by tomvandig** [comment]
@favreau84 In terms of side effects: the hierarchy of objects is separate from their placement, so the modification you did should be correct. However, obviously I would like to solve the problem without modifying the IFC 😄 

I will look at a way to easily do what @vegarringdal suggests, there's already an open issue in web-ifc about this, and it sounds like a very good idea.

About the inverted transforms: I think you should forget about the idea for now, the only advantage on top of the COORDINATE_TO_ORIGIN is that you can visualize multiple far away models that are also far away from eachother, which is a different edge case. What you did with the site is essentially the same thing: undoing the transformation of the site for all elements.

**Comment by favreau84** [comment]
@tomvandig , great ! Is the COORDINATE_TO_ORIGIN implementation intended to be called from web-ifc-three at some point ?

**Comment by tomvandig** [comment]
Please see https://github.com/tomvandig/web-ifc/blob/main/examples/usage/src/coordination.ts for an example how you can retrieve the coordinated position.

**Comment by favreau84** [comment]
@tomvandig , great ! Have you scheduled to implement it for the web-ifc-three lib ?

**Comment by agviegas** [comment]
Sorry, we forgot to mention it here with all the fuss of this month 🙂 It's already solved in the current version. You just need to use the following code, and the model should display in the origin, thus solving the nummerical stability issue:

```js
       ifcLoader.ifcManager.applyWebIfcConfig({
            COORDINATE_TO_ORIGIN: true
        })
```
