### ISSUE TITLE
Round surface coming faceted

### ISSUE THREAD

**Issue by cesarecaoduro** [IFCjs/web-ifc-three#67]
![2021-11-18 10_40_06-https___tomvandig github io_web-ifc_examples_viewer_index html and 6 more pages ](https://user-images.githubusercontent.com/26373891/142788526-918b28b6-1efb-4021-b76f-e2007b341249.jpg)

[Link to the model](https://1drv.ms/u/s!AsVTLaRAja9-g68sNwYW4F-eYngg4A?e=iLXl6h)

**Comment by agviegas** [comment]
Hey, you should be able to control the number of segments through [the configuration of web-ifc](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/api#applywebifcconfig). Right now we are based in polygons, and there is no plans of supporting pure curves due to how Three.js works. Hopefully this helps!
