### ISSUE TITLE
Export of space boundaries

### ISSUE THREAD

**Issue by MadsHolten** [IFCjs/web-ifc-three#96]
web-ifc-three generates mesh geometries for building elements and spaces but not for space boundaries although these do also have a geometrical representation.

Here is an example of properties that exist on an instance of *IfcRelSpaceBoundary*:

```json
{
    "expressID": 38919,
    "type": 3451746338,
    "GlobalId": {
        "type": 1,
        "value": "3Zrva4Xaj2$eTT3wN1QGk6"
    },
    "OwnerHistory": {
        "type": 5,
        "value": 33
    },
    "Name": {
        "type": 1,
        "value": "1stLevel"
    },
    "Description": null,
    "RelatingSpace": {
        "type": 5,
        "value": 3707
    },
    "RelatedBuildingElement": {
        "type": 5,
        "value": 22798
    },
    "ConnectionGeometry": {
        "type": 5,
        "value": 3724
    },
    "PhysicalOrVirtualBoundary": {
        "type": 3,
        "value": "PHYSICAL"
    },
    "InternalOrExternalBoundary": {
        "type": 3,
        "value": "EXTERNAL"
    }
}
```

This video demonstrates how the space boundaries of a model could look. In the example, the space boundaries are extracted with ifcopenshell for Python, exported as STL and loaded in a ThreeJS scene:
[VIDEO](https://www.youtube.com/watch?v=zeT-s1mjLzI&ab_channel=NIRASA%2FS)

The following model contains space boundaries and can be used for testing purposes:
[Duplex](https://raw.githubusercontent.com/MadsHolten/BOT-Duplex-house/master/Model%20files/IFC/Duplex.ifc).

**Comment by agviegas** [comment]
Hey, I've tried this and the definition of the geometry of those spaces is _slightly different_ to the definition of the geometry of building elements, so it's going to take some time until we are able to implement this in web-ifc. 

I'm closing this because this belongs to the realm of web-ifc. Would you please open it in [web-ifc](https://github.com/tomvandig/web-ifc)? Otherwise I can do it myself. Thanks!
